import java.net.*;
import java.io.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 3marproof
 */
public class chatbox extends javax.swing.JFrame {

    /**
     * Creates new form chatbox
     */                
            
            public chatbox() {
        initComponents();
       output=null;
    }
            DataOutputStream output;
            
    public void serverside(ServerSocket connection) {
    
        try {
          Socket connection2 = connection.accept();
          output = new DataOutputStream(connection2.getOutputStream());
          BufferedReader input = new BufferedReader(new InputStreamReader(connection2.getInputStream()));
          
            while(true) {
             
             jTextArea1.setText( jTextArea1.getText()+ "Guest: " + input.readLine()+ "\n");
              
             }
            
        }
        catch(IOException e) {
            
             System.err.println("Server IOException ");
        
        }
    
    }
    
    public void clientside(Socket connection) {
    
    try {
          
             BufferedReader input = new BufferedReader(new InputStreamReader(connection.getInputStream()));
             output = new DataOutputStream(connection.getOutputStream());
             
             while(true) {
             
             jTextArea1.setText( jTextArea1.getText() + "Guest: " + input.readLine()+ "\n");
              
             }
              
          }
          
          catch(IOException e) {
          
              System.err.println("Client IOException");
          
          }
          
          }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        sendtext();
    }                                        

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
                
    }                                           

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {                                       
            
         if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            
             sendtext();
             
        }
        
    }                                      

    private void sendtext() {
        try {
    output.writeUTF(jTextField2.getText());
    output.flush();
    
    jTextArea1.setText("You: " + jTextArea1.getText() + jTextField2.getText()+ "\n");
    jTextField2.setText("");
            }
        
        catch (IOException e) {
        
            System.err.println("Client IOException");
        
        }
    
    }
    
    /**
     * @param args the command line arguments
     */  

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration                   
}
